server:
  port: 8082
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 1
    accept-count: 1
    connection-timeout: 20000



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: likelion
    password: likelion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:schema.sql
#  session:
#    jdbc:
#      initialize-schema: always


logging:
  level:
    org.hibernate.type.descriptor.sql: info

custom:
  env: ${CUSTOM_ENV:dev}



